spring:
  application:
    name: registry
server:
  port: 8081

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    services-url:
      defaultZone: http://localhost:${server.port}/eureka/